## Experiment -> 1

1. Create 1D, 2D, and 3D tensors using PyTorch and NumPy.

In [14]:
import torch
import numpy as np

t1 = torch.tensor([1, 2, 3, 9, 24])
print("1D Tensor:", t1)

t2 = torch.tensor([[1, 2, 5], [3, 4,8]])
print("2D Tensor:", t2)

t3 = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3D Tensor:", t3)


1D Tensor: tensor([ 1,  2,  3,  9, 24])
2D Tensor: tensor([[1, 2, 5],
        [3, 4, 8]])
3D Tensor: tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


In [15]:
n1 = np.array([1, 2, 3])

n2 = np.array([[1, 2], [3, 4]])

n3 = np.array([[[1, 2], [3, 4]],[[5, 6], [7, 8]]])

print("NumPy 1D array: ", n1)
print("NumPy 2D array: ", n2)
print("NumPy 3D array: ", n3)

NumPy 1D array:  [1 2 3]
NumPy 2D array:  [[1 2]
 [3 4]]
NumPy 3D array:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


2. Show Basic Operations: Element-wise addition, subtraction, multiplication, and division.

In [3]:
a = torch.tensor([10, 20, 30])
b = torch.tensor([2, 4, 5])

add=a+b
print("\nAddition:", add)
sub=a-b
print("Subtraction:", sub)
mul=a*b
print("Multiplication:", mul)
div=a/b
print("Division:", div)


Addition: tensor([12, 24, 35])
Subtraction: tensor([ 8, 16, 25])
Multiplication: tensor([ 20,  80, 150])
Division: tensor([5., 5., 6.])


3.  Dot product and matrix multiplication.

In [ ]:
x_pt = torch.tensor([1, 2, 3])
y_pt = torch.tensor([4, 5, 6])
print("PyTorch Dot Product:", torch.dot(x_pt, y_pt))

m1_pt = torch.tensor([[1, 2], [3, 4]])
m2_pt = torch.tensor([[5, 6], [7, 8]])
print("PyTorch Matrix Multiplication:", torch.matmul(m1_pt, m2_pt))


PyTorch Dot Product: tensor(32)
PyTorch Matrix Multiplication:
 tensor([[19, 22],
        [43, 50]])


4. Indexing and Slicing examples (Boolean masking, extracting subtensors)

In [ ]:
t_pt = torch.tensor([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("PyTorch Element:", t_pt[1, 2])
print("PyTorch Rows:", t_pt[:2])
print("PyTorch Column:", t_pt[:, 1])

mask_pt = t_pt > 50
print("PyTorch Boolean Mask:", t_pt[mask_pt])

print("PyTorch Sub-tensor:", t_pt[0:2, 1:3])



PyTorch Element: tensor(60)
PyTorch Rows:
 tensor([[10, 20, 30],
        [40, 50, 60]])
PyTorch Column:
 tensor([20, 50, 80])
PyTorch Boolean Mask:
 tensor([60, 70, 80, 90])
PyTorch Sub-tensor:
 tensor([[20, 30],
        [50, 60]])


5. Use .view(), .reshape(), .unsqueeze(), and .squeeze() in PyTorch.

In [5]:
p_pt = torch.arange(1, 9)
print("Original PyTorch tensor:", p_pt)
print("Shape:", p_pt.shape)

print("Using view(4, 2):")
print(p_pt.view(4, 2))

Original PyTorch tensor: tensor([1, 2, 3, 4, 5, 6, 7, 8])
Shape: torch.Size([8])
Using view(4, 2):
tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])


In [6]:
print("Using reshape(2, 4):")
print(p_pt.reshape(2, 4))

Using reshape(2, 4):
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


In [7]:
print("Unsqueeze at dim=0:")
row_tensor = p_pt.unsqueeze(0)
print("Shape:", row_tensor.shape)
print(row_tensor)

print("Unsqueeze at dim=1:")
col_tensor = p_pt.unsqueeze(1)
print("Shape:", col_tensor.shape)
print(col_tensor)

Unsqueeze at dim=0:
Shape: torch.Size([1, 8])
tensor([[1, 2, 3, 4, 5, 6, 7, 8]])
Unsqueeze at dim=1:
Shape: torch.Size([8, 1])
tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8]])


In [8]:
print("Squeeze after unsqueeze:")
print("Shape:", p_pt.unsqueeze(0).squeeze().shape)

p_np = np.arange(1, 9)
print("NumPy reshape(4, 2):")
print(p_np.reshape(4, 2))

Squeeze after unsqueeze:
Shape: torch.Size([8])
NumPy reshape(4, 2):
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


6. Compare with .reshape in Numpy Broadcasting- Perform operations with tensors of different shapes. In-place vs Out-of-place operations

In [9]:
A_pt = torch.tensor([[1, 2, 3], [4, 5, 6]])
B_pt = torch.tensor([10, 20, 30])
print("PyTorch Broadcasting Result:")
print(A_pt + B_pt)

PyTorch Broadcasting Result:
tensor([[11, 22, 33],
        [14, 25, 36]])


In [10]:
A_np = np.array([[1, 2, 3], [4, 5, 6]])
B_np = np.array([10, 20, 30])
print("NumPy Broadcasting Result:")
print(A_np + B_np)

NumPy Broadcasting Result:
[[11 22 33]
 [14 25 36]]


In [11]:
x_pt = torch.tensor([1, 2, 3])
y_pt = x_pt + 5
print("PyTorch Out-of-place Result:", y_pt)
x_pt.add_(5)
print("PyTorch In-place Result:", x_pt)

PyTorch Out-of-place Result: tensor([6, 7, 8])
PyTorch In-place Result: tensor([6, 7, 8])


In [12]:
x_np = np.array([1, 2, 3])
y_np = x_np + 5
print("NumPy Out-of-place Result:", y_np)
x_np += 5
print("NumPy In-place Result:", x_np)

NumPy Out-of-place Result: [6 7 8]
NumPy In-place Result: [6 7 8]
